stages:
  - deploy

publish:
  stage: deploy
  image: python:3.9
  rules:
    - if: $CI_COMMIT_TAG # This will run the job only when a new tag is pushed
  script:
    - pip install --upgrade pip
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${PYPI_TOKEN} TWINE_USERNAME=__token__ python -m twine upload dist/*
